export const GAME_PHASES = {
  LOBBY: "LOBBY",
  PACK_SELECTION: "PACK_SELECTION",
  GAME_READY: "GAME_READY",
  JUDGE_SELECTION: "JUDGE_SELECTION",
  ROUND_START: "ROUND_START",
  SCENARIO: "SCENARIO",
  RESPONSE_SELECTION: "RESPONSE_SELECTION",
  DEFENSE: "DEFENSE",
  CALL_FOLD: "CALL_FOLD",
  RESOLVE_DECISIONS: "RESOLVE_DECISIONS",
  JUDGE_PICK: "JUDGE_PICK",
  STAND_ALONE: "STAND_ALONE",
  STAND_ALONE_DEFENSE: "STAND_ALONE_DEFENSE",
  STAND_ALONE_VERDICT: "STAND_ALONE_VERDICT",
  COWARD_ROUND: "COWARD_ROUND",
  NO_ESCAPE_SELECTION: "NO_ESCAPE_SELECTION",
  NO_ESCAPE_DEFENSE: "NO_ESCAPE_DEFENSE",
  NO_ESCAPE_VERDICT: "NO_ESCAPE_VERDICT",
  ROUND_RESULT: "ROUND_RESULT",
  GAME_RESULT: "GAME_RESULT",
} as const;

export type GamePhase = (typeof GAME_PHASES)[keyof typeof GAME_PHASES];
